version: "3.3"
services: 
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: on-failure
    ports: 
      - 3307:3306
    environment: 
      MYSQL_DATABASE: myebuydb
      MYSQL_USER: nir
      MYSQLPASSWORD: superduper100
      MYSQL_ROOT_PASSWORD: superduper100
      